version: '3.8'
services:
  mongodb:
    image: mongo:5.0.26
    container_name: mongodb-users
    ports:
      - "27018:27017"
    volumes:
      - mongodb_users:/data/db
    environment:
      MONGO_INITDB_DATABASE: users
    healthcheck:
      test:
        [
          "CMD",
          "mongo",
          "--quiet",
          "127.0.0.1/test",
          "--eval",
          "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

volumes:
  mongodb_users: